[workspace]
resolver = "2"
members = [
    "__test__",
    "package",
]

[workspace.dependencies]
async-std = "^1.13.0"

[workspace.dependencies.filego]
path = "./package"
features = [
    "async-std",
    "tokio",
]
