[package]
name = "__test__"
edition = "2024"
publish = false

[dependencies]
async-std = { workspace = true }
filego = { workspace = true }
tokio = { version = "^1.40.0", features = ["macros", "rt"] }
